[package]
name = "learn-cpal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
ringbuf = "0.2.2"
anyhow = "1.0.0"
spectrum-analyzer = "1.2.6"